## Filament Translatable Fields (asignua/filament-translatable-fields)

- Storage is `spatie/laravel-translatable` (`HasTranslations`). A translatable field is wrapped in locale tabs: `Asignua\FilamentTranslatableFields\Forms\TranslatableTabs::make('title', fn (string $locale) => TextInput::make('title'))` or `Translatable::field(TextInput::make('title'))`. Each language is a separate input bound to `title.{locale}`, so the state is an array `['uk' => '…', 'en' => '…']` — there is NO global locale switcher.
- Works unchanged inside `Repeater`, `Builder` blocks, `->relationship()` repeaters and on model-less settings pages. Never add `title_uk` / `title_en` columns or a locale switcher for this.
- Required: `->requiredDefault()`, `->requiredIn(['uk'])`, `->requiredAll()`, `->requiredAny()`. Other options: `->locales([...])`, `->copyFromDefault(false)`, `->emptyBadges()` (opt-in "empty" tab badge; makes inputs `live(onBlur: true)`).
- Do not call `afterStateHydrated()` on the inner field (the plugin uses it to read the record) and do not name the factory field differently from the attribute.
- Languages: `TranslatableFields::locales(['uk', 'en'])` in a service provider, or config `filament-translatable-fields.locales`, or spatie's `translatable.locales`.
- Saving: Filament's `fill()` works because spatie accepts a locale map. `use HandlesTranslatableFields;` on Create/Edit pages turns `null` languages into `''` (spatie ignores a missing key and would keep the old text). For models with `$guarded = ['*']` call `$this->fillTranslations($record, $data)` and save.
- Lists/infolists: `TranslatableColumn::make('title')->searchAcrossLocales()->sortableByLocale()`, `TranslatableEntry::make('title')`. They fall back across languages with a `[en]` marker and never write anything back; do not use them (or `TranslatedValue`) on the public site or to hydrate a form.
- Spatie hides `''` from `getTranslations()`; assert cleared languages through `getRawOriginal()` or `getTranslation($field, $locale, false)`.
